### ISSUE TITLE
Multiple malfunctions on roku with rarflix's plex implementation for this bundle

### ISSUE THREAD

**Issue by klikevil** [NotVinny/Motherless.bundle#2]
Sorry for the lack of details, but thumbnails no longer appear to be working after roku's recent unfathomable decision to scrap support for plex classic ( to go ahead and help make users aware there is a way to get that back going to go ahead and include the link to the project to the clone of it [https://github.com/ljunkie/rarflix](plex classic - aka rarflix)  --- you're welcome for that by the way roku users.  ).  Anyways several functionalities aren't working as intended now on roku.  For instance accessing next page doesn't always work on tags and thumbnails have completely vanished for all content other than the default icons, it appears to fail to load them on the channel itself.  I'm also going to use this bug report as an excuse to beg you kindly to make a heavy-r channel as well as they don't censor their content either as motherless apparently allows for users to have fantasy rape videos.

**Comment by NotVinny** [comment]
Made some quick changes today (including merging the v1.1 branch into main, forgot to accept my own pull request from like years ago... not sure what happened there). Fixed thumbnails, and accommodated for Motherless now using HTTPS. You should be back up and running, but let me know if you find any more issues. This is an alternate account of mine (gotta hide my identity, you know), but I've finally started monitoring this account's e-mail on my phone, so I'll be a little bit more in-tune for issues and whatnot coming from GitHub. No promises that I'll always be quick to react, but hopefully I should be a bit better in the future.

As far as Heavy-R, first I've ever heard of the site. Not going to commit to creating any new channels any time soon, but I'll keep that one in mind if I ever do.
